# Generated by Django 3.2.9 on 2021-12-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', '-creation']},
        ),
    ]
